name: hola-mundo
on: push
jobs:
  hola-mundo-node-jobs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar index.js
        run: node index.js